### ISSUE TITLE
Code review before publishing

### ISSUE THREAD

**Issue by Planeshifter** [distributions-io/uniform-pdf#1]

**Comment by kgryte** [comment]
Reviewed. Made changes; mainly related to documentation and formatting (see commit history). May want to give your own final once over before publishing. Things look good on my end.

**Comment by Planeshifter** [comment]
Published. I added a single sentence to the README which highlights the range of possible values that the parameter(s) can take. I think we should add something like this to all the modules.

**Comment by kgryte** [comment]
Agreed. Thanks!
